export enum RouteNames {
  root = "root",
  home = "home",
  splash = "splash",
  login = "login",
  register = "register",
  forgotPassword = "forgot-password",
  enterNewPassword = "enter-new-password",
  introduction = "introduction",
  trackingMain = "tracking-main",
  trackingLocation = "tracking-location",
  bonusDetails = "bonus-detail",
  bonusList = "bonus-list",
  challengeDetails = "challenge-detail",
  notificationList = "notification-list",
  challengeCreation = "challenge creation",
  profile = "profile",
  selectLocation = "select-location",
}
